#!/bin/bash

new_version_strategy=$(perl -ne 'print "$1" if m{### new_version=\K(major|minor|patch)$}' changelog.md)
changelog=$(perl -0ne 'print $& if m{### new_version=(minor|major|patch)\n\K.*\S+.*\n(?=### new_version_end)}s' changelog.md)

if [[ -z "$changelog" ]]; then
    >&2 echo "Changelog is empty."
    exit 1
fi

if [[ -z "$new_version_strategy" ]]; then
    >&2 echo "Can't resolve new version strategy. See changelog.md"
    >&2 echo "Should contain:"
    >&2 echo -e "\t### new_version=major|minor|patch"
    >&2 echo -e "\t### new_version_end"
    exit 1
fi

echo "${new_version_strategy}"