#!/bin/bash

spec_file="${INPUT_SPEC}"
snapshot="${INPUT_SNAPSHOT}"
script_dir="$(cd "$(dirname "$0")" && pwd)"

if [[ -z "$spec_file" ]]; then
    echo "Specification file not provided. Use --spec="
    exit 1
fi
if [[ ! -f "$spec_file" ]]; then
    echo "Specification file not found at location: ${pwd}/${spec_file}"
    exit 1
fi


new_version_strategy="$(bash $script_dir/extract-new-version-changelog)" || exit 1

if ! $snapshot; then
    new_version="$(bash $script_dir/openapi-update-version --version="${new_version_strategy}" --spec="${spec_file}")" || exit 1
    $script_dir/update-changelog-version --version="${new_version}" || exit 1
else
    new_version="$(bash $script_dir/openapi-update-version --version="${new_version_strategy}" --snapshot --spec="${spec_file}")" || exit 1 
fi

echo "${new_version}"
