#!/bin/sh

spec_file="${INPUT_SPEC}"
snapshot="${INPUT_SNAPSHOT}"
script_dir="$(cd "$(dirname "$0")" && pwd)"

if [[ -z "$spec_file" ]]; then
    echo "Specification file not provided. Use --spec="
    exit 1
fi
if [[ ! -f "$spec_file" ]]; then
    echo "Specification file not found at location: ${pwd}/${spec_file}"
    exit 1
fi


new_version_strategy="$(sh $script_dir/extract-new-version-changelog)" || exit 1

if ! $snapshot; then
    new_version="$(sh $script_dir/openapi-update-version "${new_version_strategy}")" || exit 1
    sh $script_dir/update-changelog-version "${new_version}" || exit 1
else
    new_version="$(sh $script_dir/openapi-update-version "${new_version_strategy}")" || exit 1 
fi

echo "${new_version}"
