#!/bin/bash

version=$1

# Extract changelog
changelog=$(perl -0ne 'print $& if m{### new_version=(minor|major|patch)\n\K.*\S+.*\n(?=### new_version_end)}s' changelog.md)
changelog="## ${version}\n${changelog}"

# Remove changelog entry container
sed -i -E "/### new_version/,/### new_version_end/d" ./changelog.md

# Add new version change log
sed -i  "1s/^/${changelog}\n/" ./changelog.md

# Add container for future versions
container="### new_version=major|minor|patch\n\n### new_version_end\n\n"
sed -i "1s/^/${container}/" ./changelog.md

exit 0