#!/bin/bash

version=$1

container="### new_version=major|minor|patch\n\n### new_version_end\n"

# Extract changelog
changelog="$(sed -nE "/new_version=/,/new_version_end/p" changelog.md | tail -n +2 | head -n -1)"
changelog="## ${version}\n${changelog}"
# Add new version change log

echo "$(echo -e "$container" ; echo -e "$changelog" ; sed -E "/### new_version/,/### new_version_end/d" ./changelog.md)" > ./changelog.md.new

mv ./changelog.md{.new,}